baseurl: https://cbcs-lib-rworkshop2021.netlify.app/
languageCode: en-us
title: R workshop website for CBCS and LIB
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: GitHub
      url: https://github.com/seaCatKim/CBCS-LIB_Rworkshop
    - name: Twitter
      url: https://twitter.com/UQ_Library
    - name: CBCS
      url: //https://cbcs.centre.uq.edu.au/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: The accompanying resource for a 2-day R workshop at The University of Queensland run by the Centre for Biodiversity and Conservation Science and the University Library.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 80
    url: uq_logo.png
    width: 80
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
